//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmProgramIndicator
    {
        public System.Guid Id { get; set; }
        public System.Guid ProgramId { get; set; }
        public System.Guid IndicatorId { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Indicator Indicators { get; set; }
    }
}
